export const SUBSCRIPTION_POLL_INTERVAL = process.env.SUBSCRIPTION_POLL_INTERVAL || 10000
export const TARGET_USER_UPDATE_INTERVAL = process.env.TARGET_USER_UPDATE_INTERVAL || 10000
export const MAX_FAILED_FETCH_INTERVAL = process.env.MAX_FAILED_FETCH_INTERVAL || 60000
export const WS_PORT = process.env.PORT || 8765
